
CC = gcc

CFLAG = -Wall -Wextra

CPPFLAGS = -I ./include

SRC = src/ \

NAME = fonctions

OBJ = $(SRC:.c=.o) # 

all: $(NAME)

$(NAME) : $(OBJ)
	$(CC) $(OBJ) -o $(NAME) $(CPPFLAGS) $(CFLAG)

clean : # Supprime les fichiers en .o
	rm -f $(OBJ)

fclean : clean
	rm -f $(NAME) 

re : fclean all

.PHONY : re fclean clean all